[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via-ir = true
solc = "0.8.26" # Add your specific compiler version here
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
